# Generated by Django 3.0.6 on 2020-06-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_lostdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_addPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogImage', models.FileField(upload_to='addpost/')),
                ('species', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('accessory', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'create',
            },
        ),
        migrations.CreateModel(
            name='Image_searchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogImage', models.FileField(upload_to='searchpost/')),
                ('species', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('accessory', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'create',
            },
        ),
    ]
