# Generated by Django 3.0.7 on 2020-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_lostdog', '0002_image_addpost_image_searchpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_db',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image_db',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
