# Generated by Django 3.0.7 on 2020-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_lostdog', '0003_auto_20200609_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_addpost',
            name='time',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image_searchpost',
            name='time',
            field=models.DateTimeField(max_length=100),
        ),
    ]
